---
title: "nflrushing animate"
output: html_document
date: '2022-06-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nflfastR)
library(nflreadr)
library(tidyverse)
library(gganimate)
library(ggimage)
library(glue)

options(scipen = 999)

```

load season stats and filter

```{r load season stats and filter}
season2021 <- load_player_stats(2021)
season2021 %>% view()
top_rush <- season2021 %>% 
  group_by(player_id) %>% 
    filter(season_type == "REG", sum(rushing_yards) > 936) %>% 
  ungroup()

top_rush <- top_rush %>% 
  group_by(player_name) %>% 
  mutate(cumulative_rush = cumsum(rushing_yards)) %>% 
  ungroup()

top_rush <- top_rush %>% 
  select(player_id, player_name, recent_team, week, carries, rushing_yards, rushing_tds, rushing_fumbles, rushing_epa, rushing_first_downs, fantasy_points_ppr, cumulative_rush )

top_rush$game <- seq_along(top_rush$player_name)

top_rush %>% count(player_name)
top_rush <- top_rush %>% 
  rename(team_abbr = recent_team)

top_rush <- top_rush %>% 
  left_join(teams_colors_logos, by = c("team_abbr" = "team_abbr"))

```

now for graphs

```{r now for graphs}

top_rush %>% 
  ggplot(aes(cumulative_rush, player_name, color = player_name)) +
  geom_col() + 
  transition_time(week)

top_rush %>% 
  ggplot(aes(week, cumulative_rush, group = player_name)) +
  geom_line() +
  geom_point() +
  transition_reveal(week)


top_rush %>% 
  ggplot(aes(week, cumulative_rush, group = player_name)) + 
  geom_image(aes(image = team_logo_espn), width = 0.03, alpha = 0.7)

animation <- top_rush %>%
  filter(player_name == "J.Taylor") %>% 
  ggplot(aes(week, cumulative_rush, group = player_name)) +
  geom_line() +
  geom_image(aes(image = team_logo_espn), size = .05) +
  transition_reveal(week) +
  ggtitle('Rushing Total by Week')

animate(animation, end_pause = 10)

```

Just D.Henry

```{r Just D. Henry}
dhenry <- load_player_stats(2016:2021) %>% filter(player_name == "D.Henry")

dhenry <- dhenry %>% filter(season_type == "REG")

dhenry <- dhenry %>% 
  select(player_name, recent_team, rushing_yards, rushing_epa, rushing_first_downs, season, week)

dhenry <- dhenry %>% 
  group_by(season) %>% 
  mutate(cumrush = cumsum(rushing_yards)) %>% 
  ungroup()

dhenry <- dhenry %>%
  left_join(teams_colors_logos, by = c("recent_team" = "team_abbr"))

dh <- dhenry %>% 
  ggplot(aes(week, cumrush, group = season, label = season, color = season)) +
  labs(x = "Week", 
       y = "Season Total Rushing Yards",
       title = "Derrick Henry Rushing Yards by Season",
       subtitle = "What could have happened in 2021?",
       caption = "@jmeerse  Data: nflfastR") +
  scale_x_continuous(breaks = seq(1, 17),
                     limits = c(1, 18)) +
  geom_line(size = 1) + 
  geom_text(size = 5) +
  theme_classic()

dh

animate(dh + transition_reveal(dhenry$week), end_pause = 30, width=900, height=506)


anim_save("DHenry.gif")

```

Now let's compare QBs

```{r let's compare QBs}
qbs <- load_player_stats(2017:2021) 

qbs <- qbs %>% filter(season_type == "REG")

qbs <- qbs %>% group_by(player_id) %>% 
  filter(sum(passing_yards) > 3000) %>% 
  ungroup()

#try to number by games played
qbs <- qbs %>% 
  arrange(player_id) #groups players by id, since names vary

tot_games <- qbs %>% group_by(player_id) %>% summarise(n = n())

qbs$game_no <- sequence(c(tot_games$n)) #can't believe this worked!

qbs <- qbs %>% 
  group_by(player_id) %>% 
  filter(max(game_no) > 40) %>% 
  ungroup()

qbs <- qbs %>% 
  group_by(player_id) %>% 
  mutate(cum_epa = cumsum(passing_epa)) %>% 
  ungroup()

qbs <- qbs %>% 
  left_join(teams_colors_logos, by = c("recent_team" = "team_abbr"))


qbs_image <- qbs %>%  
  group_by(player_id)  %>%  
  slice_max(order_by = game_no, n = 1)

ggplot(qbs, aes(x = game_no, 
                 y = cum_epa, 
                 group = player_id)) +
      labs(x = "game number",
            y = "cumulative passing EPA",
            title = "Total Passing EPA",
            subtitle = "Since 2017, at least 40 games played") + 
  geom_line(color = qbs$team_color) +
  geom_image(data = qbs_image, aes(x = game_no, 
                                  y = cum_epa, 
                                  image = team_logo_espn), 
             size = 0.08)

#still need key and there's at least one missing image and should either recode player names or group better (id, season, week)

```  









help!?!
```{r}
#example for stack.overflow question
name <- c("a", "a", "b", "b", "b") 
game <- c(1, 2, 1, 2, 3) 
pts <- c(3, 6, 1, 6, 7) 
cum_pts <- c(3, 9, 1, 7, 14) 

pics <- c("https://a.espncdn.com/i/teamlogos/nfl/500/buf.png", "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png", "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png", "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png", "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png")

df <- data.frame(name, game, pts, cum_pts, pics)

df %>%  
  ggplot(aes(x = game, y = cum_pts, group = name)) +
  geom_line() +
  geom_image(data = filter(df, name == "a"),aes(x = max(game), y = max(cum_pts), image = pics), size = 0.08) +
  geom_image(data = filter(df, name == "b"),aes(x = max(game), y = max(cum_pts), image = pics), size = 0.08)




```

